# app/pdf_generator.py
"""
PDF generation for LegalAId legal notices.

Uses fpdf2 to create professional legal notice documents
from the matched case data returned by the conversation pipeline.
"""
import io
from datetime import datetime

from fpdf import FPDF


class LegalNoticePDF(FPDF):
    """Custom PDF class for LegalAId notices."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "LegalAId - AI-Powered Legal Rights Assistant", align="C")
        self.ln(4)
        self.set_draw_color(200, 170, 80)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(8)

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(200, 170, 80)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(4)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, f"Generated by LegalAId on {datetime.now().strftime('%d %B %Y, %I:%M %p')}", align="L")
        self.cell(0, 6, f"Page {self.page_no()}/{{nb}}", align="R")


def _safe_text(text):
    """Ensure text is a string and replace Unicode chars unsupported by Helvetica."""
    if text is None:
        return ""
    s = str(text)
    # Replace common Unicode characters with ASCII equivalents
    replacements = {
        "\u2014": "--",   # em dash
        "\u2013": "-",    # en dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u2022": "*",    # bullet
        "\u00a0": " ",    # non-breaking space
        "\u20b9": "Rs.",  # Indian Rupee sign
        "\u2192": "->",   # right arrow
    }
    for uchar, ascii_char in replacements.items():
        s = s.replace(uchar, ascii_char)
    # Strip any remaining non-latin1 characters
    s = s.encode("latin-1", errors="replace").decode("latin-1")
    return s


def generate_legal_notice_pdf(
    domain_id: str,
    matched_sections: list[dict],
    extracted_facts: dict,
    applicable_laws: list[dict],
    confidence_flags: list[dict] | None = None,
) -> bytes:
    """
    Generate a PDF legal notice/summary document.

    Returns the PDF as raw bytes suitable for streaming to the client.
    """
    pdf = LegalNoticePDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    domain_label = _safe_text((domain_id or "").replace("_", " ").title())
    section = matched_sections[0] if matched_sections else {}
    issue_label = _safe_text((section.get("issue", "") or "").replace("_", " ").title())

    # ── Title ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(20, 30, 60)
    pdf.cell(0, 12, "Legal Case Summary", ln=True, align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, f"Domain: {domain_label} | Issue: {issue_label}", ln=True, align="C")
    pdf.cell(0, 7, f"Date: {datetime.now().strftime('%d %B %Y')}", ln=True, align="C")
    pdf.ln(8)

    # ── Separator ──
    pdf.set_draw_color(200, 170, 80)
    pdf.set_line_width(0.8)
    pdf.line(15, pdf.get_y(), pdf.w - 15, pdf.get_y())
    pdf.ln(8)

    # ── Extracted Facts ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(20, 30, 60)
    pdf.cell(0, 10, "Extracted Facts", ln=True)
    pdf.ln(2)

    if extracted_facts:
        for key, value in extracted_facts.items():
            label = _safe_text(key.replace("_", " ").title())
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 80)
            pdf.cell(60, 7, f"  {label}:", ln=False)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 7, _safe_text(value))
            pdf.ln(1)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 7, "  No facts extracted.", ln=True)

    pdf.ln(6)

    # ── Applicable Laws ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(20, 30, 60)
    pdf.cell(0, 10, "Applicable Laws", ln=True)
    pdf.ln(2)

    if applicable_laws:
        for i, law in enumerate(applicable_laws, 1):
            act = _safe_text(law.get("act", ""))
            section_num = _safe_text(law.get("section_number", ""))
            summary = _safe_text(law.get("text_summary", ""))

            # Law header
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 40, 70)
            pdf.cell(0, 7, f"  {i}. {act}, {section_num}", ln=True)

            # Law summary
            if summary:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(50, 50, 50)
                pdf.set_x(18)
                pdf.multi_cell(pdf.w - 30, 6, summary)

            pdf.ln(3)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 7, "  No applicable laws identified.", ln=True)

    pdf.ln(6)

    # ── Matched Section Details ──
    if matched_sections:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(20, 30, 60)
        pdf.cell(0, 10, "Matched Legal Sections", ln=True)
        pdf.ln(2)

        for s in matched_sections:
            issue = _safe_text(s.get("issue", "")).replace("_", " ").title()
            score = s.get("score", 0)
            notes = _safe_text(s.get("notes", ""))

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 40, 70)
            pdf.cell(0, 7, f"  Issue: {issue}  (Match: {int(score * 100)}%)", ln=True)

            if notes:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(50, 50, 50)
                pdf.set_x(18)
                pdf.multi_cell(pdf.w - 30, 6, notes)

            pdf.ln(3)

    # ── Evidence Recommendations ──
    if confidence_flags:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(20, 30, 60)
        pdf.cell(0, 10, "Evidence Recommendations", ln=True)
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 6, "  Gathering these items will strengthen your case:", ln=True)
        pdf.ln(2)

        for flag in confidence_flags:
            field = _safe_text(flag.get("field", ""))
            message = _safe_text(flag.get("message", ""))

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 80)
            pdf.cell(0, 7, f"  - {field}", ln=True)

            if message:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(70, 70, 70)
                pdf.set_x(18)
                pdf.multi_cell(pdf.w - 30, 6, message)

            pdf.ln(2)

    # ── Disclaimer ──
    pdf.ln(8)
    pdf.set_draw_color(200, 170, 80)
    pdf.set_line_width(0.3)
    pdf.line(15, pdf.get_y(), pdf.w - 15, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0,
        5,
        "DISCLAIMER: This document is generated by an AI system for informational purposes only. "
        "It does not constitute legal advice. Please consult a qualified legal professional before "
        "taking any legal action. State-specific rules and recent amendments may affect the applicability "
        "of the laws mentioned above.",
    )

    # Output as bytes
    return pdf.output()
