# app/pdf_generator.py
"""
PDF generation for LegalAId legal notices.

Uses fpdf2 to create professional legal notice documents
from the matched case data returned by the conversation pipeline.
"""
import io
from datetime import datetime

from fpdf import FPDF


# ── Colour palette ──
NAVY = (20, 30, 60)
NAVY_LIGHT = (40, 50, 90)
GOLD = (180, 150, 60)
GOLD_DARK = (160, 130, 40)
GREY_DARK = (50, 50, 50)
GREY_MID = (100, 100, 100)
GREY_LIGHT = (150, 150, 150)
CREAM_BG = (252, 249, 242)
SECTION_BG = (245, 242, 232)
WHITE = (255, 255, 255)
ACCENT_BLUE = (45, 80, 140)
ACCENT_GREEN = (30, 120, 80)


class LegalNoticePDF(FPDF):
    """Custom PDF class for LegalAId notices."""

    def header(self):
        # Subtle top accent bar
        self.set_fill_color(*GOLD)
        self.rect(0, 0, self.w, 3, "F")

        self.set_y(8)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GREY_LIGHT)
        self.cell(0, 6, "LegalAId  |  AI-Powered Legal Rights Assistant", align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-22)
        # Thin gold line
        self.set_draw_color(*GOLD)
        self.set_line_width(0.4)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(5)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GREY_LIGHT)
        self.cell(
            0,
            5,
            f"Generated by LegalAId on {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
            align="L",
        )
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="R")


def _safe_text(text):
    """Ensure text is a string and replace Unicode chars unsupported by Helvetica."""
    if text is None:
        return ""
    s = str(text)
    # Replace common Unicode characters with ASCII equivalents
    replacements = {
        "\u2014": "--",   # em dash
        "\u2013": "-",    # en dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u2022": "*",    # bullet
        "\u00a0": " ",    # non-breaking space
        "\u20b9": "Rs.",  # Indian Rupee sign
        "\u2192": "->",   # right arrow
    }
    for uchar, ascii_char in replacements.items():
        s = s.replace(uchar, ascii_char)
    # Strip any remaining non-latin1 characters
    s = s.encode("latin-1", errors="replace").decode("latin-1")
    return s


def _draw_section_heading(pdf, title, y_offset=4):
    """Draw a styled section heading with an accent bar."""
    pdf.ln(y_offset)
    # Gold accent bar on the left
    y_start = pdf.get_y()
    pdf.set_fill_color(*GOLD)
    pdf.rect(15, y_start, 3, 10, "F")

    pdf.set_x(22)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 10, title, ln=True)
    pdf.ln(3)


def _draw_key_value_row(pdf, key, value, x_start=20, key_width=55):
    """Draw a nicely formatted key–value row with proper text wrapping."""
    y_before = pdf.get_y()

    # Key
    pdf.set_x(x_start)
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(*NAVY_LIGHT)
    pdf.cell(key_width, 7, f"{key}:", ln=False)

    # Value — use multi_cell so long values wrap properly
    value_x = x_start + key_width
    value_width = pdf.w - value_x - 15
    pdf.set_x(value_x)
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*GREY_DARK)
    pdf.multi_cell(value_width, 7, _safe_text(value))

    # Ensure at least one line of spacing
    if pdf.get_y() - y_before < 7:
        pdf.ln(1)


def generate_legal_notice_pdf(
    domain_id: str,
    matched_sections: list[dict],
    extracted_facts: dict,
    applicable_laws: list[dict],
    confidence_flags: list[dict] | None = None,
) -> bytes:
    """
    Generate a PDF legal notice/summary document.

    Returns the PDF as raw bytes suitable for streaming to the client.
    """
    pdf = LegalNoticePDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=28)
    pdf.add_page()

    domain_label = _safe_text((domain_id or "").replace("_", " ").title())
    section = matched_sections[0] if matched_sections else {}
    issue_label = _safe_text(
        (section.get("issue", "") or "").replace("_", " ").title()
    )

    # ── Title Block ──
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 14, "Legal Case Summary", ln=True, align="C")
    pdf.ln(1)

    # Subtitle line
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY_MID)
    if domain_label and issue_label:
        pdf.cell(0, 7, f"Domain: {domain_label}  |  Issue: {issue_label}", ln=True, align="C")
    pdf.cell(
        0, 7, f"Date: {datetime.now().strftime('%d %B %Y')}", ln=True, align="C"
    )
    pdf.ln(4)

    # Gold separator
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(1.0)
    pdf.line(20, pdf.get_y(), pdf.w - 20, pdf.get_y())
    pdf.ln(6)

    # ── Extracted Facts ──
    _draw_section_heading(pdf, "Extracted Facts")

    if extracted_facts:
        # Light background box for the facts table
        facts_y = pdf.get_y()
        facts_items = list(extracted_facts.items())

        # Draw a subtle background
        total_height = len(facts_items) * 9 + 4
        pdf.set_fill_color(*SECTION_BG)
        pdf.rect(17, facts_y - 1, pdf.w - 34, total_height, "F")

        for key, value in facts_items:
            label = _safe_text(key.replace("_", " ").title())
            _draw_key_value_row(pdf, label, value, x_start=22, key_width=60)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(*GREY_LIGHT)
        pdf.cell(0, 7, "  No facts extracted.", ln=True)

    pdf.ln(6)

    # ── Applicable Laws ──
    _draw_section_heading(pdf, "Applicable Laws")

    if applicable_laws:
        for i, law in enumerate(applicable_laws, 1):
            act = _safe_text(law.get("act", ""))
            section_num = _safe_text(law.get("section_number", ""))
            summary = _safe_text(law.get("text_summary", ""))

            # Numbered law heading
            pdf.set_x(20)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*ACCENT_BLUE)
            pdf.cell(0, 8, f"{i}. {act}, {section_num}", ln=True)

            # Law summary in a slightly indented block
            if summary:
                pdf.set_x(26)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*GREY_DARK)
                pdf.multi_cell(pdf.w - 42, 6, summary)

            pdf.ln(4)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(*GREY_LIGHT)
        pdf.cell(0, 7, "  No applicable laws identified.", ln=True)

    pdf.ln(4)

    # ── Matched Legal Sections ──
    if matched_sections:
        _draw_section_heading(pdf, "Matched Legal Sections")

        for s in matched_sections:
            issue = _safe_text(s.get("issue", "")).replace("_", " ").title()
            score = s.get("score", 0)
            notes = _safe_text(s.get("notes", ""))
            pct = int(score * 100)

            # Issue row with match badge
            pdf.set_x(20)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*NAVY)
            issue_text = f"Issue: {issue}"
            issue_w = pdf.get_string_width(issue_text) + 4
            pdf.cell(issue_w, 8, issue_text, ln=False)

            # Match percentage badge
            if pct >= 80:
                badge_color = ACCENT_GREEN
            elif pct >= 50:
                badge_color = GOLD_DARK
            else:
                badge_color = GREY_MID

            badge_text = f"Match: {pct}%"
            badge_w = pdf.get_string_width(badge_text) + 10
            badge_x = pdf.get_x() + 4
            badge_y = pdf.get_y() + 1
            pdf.set_fill_color(*badge_color)
            pdf.set_draw_color(*badge_color)
            pdf.rect(badge_x, badge_y, badge_w, 6, "DF")
            pdf.set_xy(badge_x, badge_y)
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*WHITE)
            pdf.cell(badge_w, 6, badge_text, align="C")
            pdf.ln(10)

            # Notes
            if notes:
                pdf.set_x(26)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*GREY_DARK)
                pdf.multi_cell(pdf.w - 42, 6, notes)

            pdf.ln(4)

    # ── Evidence Recommendations ──
    if confidence_flags:
        _draw_section_heading(pdf, "Evidence Recommendations")

        pdf.set_x(20)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GREY_MID)
        pdf.cell(0, 6, "Gathering these items will strengthen your case:", ln=True)
        pdf.ln(3)

        for idx, flag in enumerate(confidence_flags, 1):
            field = _safe_text(flag.get("field", ""))
            message = _safe_text(flag.get("message", ""))

            # Bullet-style field name
            pdf.set_x(22)
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(*NAVY_LIGHT)
            pdf.cell(0, 7, f"{idx}. {field}", ln=True)

            if message:
                pdf.set_x(28)
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(*GREY_DARK)
                pdf.multi_cell(pdf.w - 44, 5.5, message)

            pdf.ln(3)

    # ── Disclaimer ──
    pdf.ln(6)
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.4)
    pdf.line(20, pdf.get_y(), pdf.w - 20, pdf.get_y())
    pdf.ln(5)

    # Disclaimer in a subtle box
    disclaimer_y = pdf.get_y()
    disclaimer_text = (
        "DISCLAIMER: This document is generated by an AI system for informational "
        "purposes only. It does not constitute legal advice. Please consult a "
        "qualified legal professional before taking any legal action. State-specific "
        "rules and recent amendments may affect the applicability of the laws "
        "mentioned above."
    )

    pdf.set_fill_color(248, 245, 238)
    pdf.set_font("Helvetica", "I", 7.5)
    # Calculate height needed
    # Roughly 80 chars per line at this font size across the page width
    num_lines = max(1, len(disclaimer_text) // 90 + 1)
    box_h = num_lines * 5 + 6
    pdf.rect(18, disclaimer_y - 1, pdf.w - 36, box_h, "F")

    pdf.set_xy(22, disclaimer_y + 1)
    pdf.set_text_color(*GREY_MID)
    pdf.multi_cell(pdf.w - 44, 4.5, disclaimer_text)

    # Output as bytes
    return pdf.output()
